### ISSUE TITLE
怎么编译出二进制可执行文件bert_model_example？

### ISSUE THREAD

**Issue by ShenYounger** [Tencent/TurboTransformers#37] opened 2020-05-12 08:10 UTC
我执行的步骤如下：
1. cd example/cpp
2. mkdir build
3. cd build
4. cmake ..
5. make

其中第4步输出为：
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:22 (add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "bert_model_example" links to some libraries for which the
  linker must search:

    tt_npz_loader, tt_layers, tt_kernels

  and other libraries with known full path:

    /workspace/TurboTransformers/example/cpp/build/libbert_model.a

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /workspace/TurboTransformers/example/cpp/build

第五步输出为
Scanning dependencies of target bert_model
[ 25%] Building CXX object CMakeFiles/bert_model.dir/bert_model.cpp.o
In file included from /workspace/TurboTransformers/example/cpp/bert_model.cpp:14:0:
/workspace/TurboTransformers/example/cpp/bert_model.h:20:10: fatal error: dlpack/dlpack.h: No such file or directory
 **#include "dlpack/dlpack.h"**
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/bert_model.dir/build.make:62: recipe for target 'CMakeFiles/bert_model.dir/bert_model.cpp.o' failed
make[2]: *** [CMakeFiles/bert_model.dir/bert_model.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/bert_model.dir/all' failed
make[1]: *** [CMakeFiles/bert_model.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by feifeibear** [comment] 2020-05-12 08:12
没有下载全，submodule的代码都没有
git clone XXXX --recursive

**Comment by ShenYounger** [comment] 2020-05-12 08:13
> 没有下载全，submodule的代码都没有
> git clone XXXX --recursive

确认了一下，submodule都是在的

**Comment by ShenYounger** [comment] 2020-05-12 08:13
> 没有下载全，submodule的代码都没有
> git clone XXXX --recursive

确认了一下，submodule都在。

total 24
drwxr-xr-x  9 root root  164 May 11 06:45 ./
drwxr-xr-x 13 root root 4096 May 12 08:06 ../
-rw-r--r--  1 root root 2847 May 11 06:45 CMakeLists.txt
drwxr-xr-x 15 root root 4096 May 11 06:48 Catch2/
drwxr-xr-x  8 root root  211 May 11 06:48 FP16/
drwxr-xr-x  5 root root  300 May 11 06:48 abseil/
drwxr-xr-x  8 root root  252 May 11 06:51 cub/
drwxr-xr-x  8 root root  220 May 11 06:51 dlpack/
-rw-r--r--  1 root root 1513 May 11 06:45 eigen.cmake
drwxr-xr-x  8 root root  248 May 11 06:51 loguru/
-rw-r--r--  1 root root 1526 May 11 06:45 openblas.cmake
drwxr-xr-x  7 root root 4096 May 11 06:51 pybind11/

**Comment by feifeibear** [comment] 2020-05-12 08:22
麻烦确认里面的内容也都在，比如
cat dlpack/include/dlpack/dlpack.h
或者执行一下
git submodule update

**Comment by ShenYounger** [comment] 2020-05-12 08:24
> 麻烦确认里面的内容也都在，比如
> cat dlpack/include/dlpack/dlpack.h
> 或者执行一下
> git submodule update

确定都在。感觉example/cpp下的CMakeLists.txt，好像有些问题，没有把一些头文件目录包含进去。

**Comment by feifeibear** [comment] 2020-05-12 08:27
哦，发现你编译方法不对，你按照readme编译example的二进制自动编译出来了，不要自己到cpp/example里面搞，那样没有include到3rd的文件。
如果你想在其他项目里用turbo，可以使用add_subdirectory方式，我们过一段时间会提供一个serving例子

**Comment by ShenYounger** [comment] 2020-05-12 08:54
> 哦，发现你编译方法不对，你按照readme编译，example的二进制会被顺带编译出来了，不要自己到cpp/example里面搞，那样没有include到3rd的文件。
> 如果你想在其他项目里用turbo，可以使用add_subdirectory方式，我们过一段时间会提供一个serving例子

恩 明白了。我在TurboTransformers主目录里，编译就行了。可以把bert_model_example顺便编译出来。

多谢。

**Comment by feifeibear** [comment] 2020-05-12 08:57
Happy turboing.
The issue is solved and I closed it.

**Closed by feifeibear** 2020-05-12 08:57 UTC
